### PR TITLE
Fix sluggish panning on some browsers

### PR DESCRIPTION
**Pull request by jarmo**
It seems that at least Firefox on Windows has changed in a way which causes panning on mousemove to be quite sluggish (this was not a problem with older Firefox versions).

This PR fixes this problem by debouncing `mousemove` events for 5 millis before actually doing the panning.

In addition `mousemove` event listener is configured as passive which should in theory be more performance-friendly too.

### CODE REVIEW

**Comment by tsibley** [comment]
Thanks for your continued contributions!

**Comment by tsibley** [comment]
You might also take a peek at https://github.com/tsibley/flickr-zoom/commit/1e3a7ac6c2725a7ec84a6f7a5d10a750df40d839, which seems to improve the feel of it a lot for me.

**Comment by jarmo** [comment]
https://github.com/tsibley/flickr-zoom/commit/1e3a7ac6c2725a7ec84a6f7a5d10a750df40d839 seems to be pretty okay indeed! However with the `throttle` introduced by this PR this seems a little sluggish for my taste. I propose to remove `throttle` when going with this route. What do you think?

**Comment by tsibley** [comment]
Sure. I'm not sure I can tell the difference, but it doesn't seem like the throttle is needed in my very limited testing.

**Pull request merged**
